---
shellPath: "/bin/bash"
# Use this for example to add additional packages to extend telegrammy's possibilties
initCommand: "apk add git ansible"
pollInterval: 5

responseJobs:

  # Simple reponse job
  - trigger: "Hello"
    message: "world!"

  # Get the current telegrammy configuration
  - trigger: "Configuration"
    command: "cat $TELEGRAMMY_CONFIG_PATH"
    message: "```\n%s```"
    parseMode: MarkdownV2
    escapeCharacters:
      - "`"

  # Simple way to delete the current conversation context with ChatGPT
  - trigger: "Reset"
    command: "rm -f $CHAT_GPT_CONVERSATION_PATH"
    message: "ChatGPT conversation reset"

cronJobs:

  # Simple cron job
  - schedule: "20 16 * * *"
    message: "[Open this link](https://example.com)"
    parseMode: MarkdownV2
