---
shellPath: "/bin/bash"
# Example use of the initCommand to install additional packages and import a SSH private key
initCommand: |
  apk add openssh git ansible
  mkdir ~/.ssh
  echo "-----BEGIN OPENSSH PRIVATE KEY-----
  ...
  ...
  ...
  ...
  ...
  -----END OPENSSH PRIVATE KEY-----" > ~/.ssh/id_ed25519
  chmod 400 ~/.ssh/id_ed25519
pollInterval: 5

responseJobs:

  # Simple reponse job
  - trigger: "Hello"
    message: "world!"

  # Get the current telegrammy configuration
  - trigger: "Configuration"
    command: "cat /etc/telegrammy/config.yaml"
    message: "```\n%s```"
    parseMode: MarkdownV2
    escapeCharacters:
      - "`"

  # Simple way to delete the current conversation context with ChatGPT
  - trigger: "Reset"
    command: "rm -f /etc/telegrammy/conversation"
    message: "ChatGPT conversation reset"

  # Example to execute a ansible playbook (the necessary dependencies are installed via initCommand)
  - trigger: "Update"
    command: |
      git clone --quiet https://github.com/kymzky/ansible-homelab.git
      cd ansible-homelab
      echo "[defaults]
      host_key_checking = False" > ansible.cfg
      git pull --quiet
      ansible-playbook -i inventory/prod.yaml playbooks/update.yaml > /tmp/ansible.log
      cat /tmp/ansible.log
    message: "Update prod:\n```\n%s```"
    parseMode: MarkdownV2
    escapeCharacters:
      - "`"

cronJobs:

  # Simple cron job
  - schedule: "20 16 * * *"
    message: "[Open this link](https://example.com)"
    parseMode: MarkdownV2
